import json
from bygram.core.types import DeserializedObject
from bygram.core.wrapper import TdLibWrapper
from bygram.types.base import Function, ObjectBase, T
from typing import Any

__all__ = ['serialize_object', 'deserialize_object']

class CustomJSONEncoder(json.JSONEncoder):
    def default(self, o: Any) -> Any: ...

def serialize_object(obj: ObjectBase, extra: Any | None = None) -> bytes: ...
def deserialize_object(obj: bytes) -> DeserializedObject: ...

class SerializedWrapper:
    def __init__(self, wrapper: TdLibWrapper) -> None: ...
    def create_client(self) -> int: ...
    def send(self, client_id: int, func: Function, extra: Any | None = None): ...
    def receive(self, timeout: float) -> DeserializedObject | None: ...
    def execute(self, func: Function[T]) -> T: ...
