import ctypes
from _typeshed import Incomplete

class TdLibWrapper:
    cdll: Incomplete
    def __init__(self, cdll: ctypes.CDLL) -> None: ...
    def create_client(self) -> int: ...
    def send(self, client_id: int, request: bytes) -> None: ...
    def receive(self, timeout: float) -> bytes | None: ...
    def execute(self, request: bytes) -> bytes: ...

def load_library(path: str) -> TdLibWrapper: ...
