from _typeshed import Incomplete
from bygram.core.serializer import SerializedWrapper as SerializedWrapper
from bygram.core.types import T as T
from bygram.executor import Executor as Executor
from bygram.types.base import Function as Function
from bygram.types.raw import AuthorizationStateClosed as AuthorizationStateClosed, Close as Close, UpdateAuthorizationState as UpdateAuthorizationState

logger: Incomplete
SHUTDOWN_TIMEOUT: int

class Client:
    id: Incomplete
    def __init__(self, client_id: int, executor: Executor) -> None: ...
    async def execute(self, function: Function[T], timeout: float = 30) -> T: ...

class ClientManager:
    def __init__(self, executor: Executor, wrapper: SerializedWrapper) -> None: ...
    def create_client(self) -> Client: ...
    def get_client_by_id(self, client_id: int): ...
    async def handle_authorization_state_update(self, update: UpdateAuthorizationState, client_id: int): ...
    async def shutdown(self) -> None: ...
