from _typeshed import Incomplete
from bygram.core.listener import EventListener as EventListener
from bygram.core.types import DeserializedObject as DeserializedObject
from bygram.executor import Executor as Executor
from bygram.routing.dispatcher import Dispatcher as Dispatcher

class EventsLoop:
    listener: Incomplete
    executor: Incomplete
    dispatcher: Incomplete
    def __init__(self, listener: EventListener, executor: Executor, dispatcher: Dispatcher | None = None) -> None: ...
    def attach_dispatcher(self, dp: Dispatcher): ...
    def start_listening(self) -> None: ...
    async def join(self) -> None: ...
    async def shutdown(self) -> None: ...
