import asyncio
from _typeshed import Incomplete
from bygram.client_manager import Client as Client, ClientManager as ClientManager
from bygram.core.listener import EventListener as EventListener
from bygram.core.serializer import SerializedWrapper as SerializedWrapper
from bygram.core.types import T as T
from bygram.core.wrapper import load_library as load_library
from bygram.executor import Executor as Executor
from bygram.routing.dispatcher import Dispatcher as Dispatcher
from bygram.routing.middlewares import ClientManagerMiddleware as ClientManagerMiddleware
from bygram.strategy import EventsLoop as EventsLoop
from bygram.types.base import Function as Function
from enum import Enum

logger: Incomplete

class LibraryState(Enum):
    created = ...
    initalized = ...
    shutting_down = ...
    shutdowned = ...

def create_library_manager(path: str, loop: asyncio.AbstractEventLoop | None = None, receive_timeout: float = 60): ...

class LibraryManager:
    def __init__(self, client_manager: ClientManager, event_loop: EventsLoop, serialized_wrapper: SerializedWrapper) -> None: ...
    async def __aenter__(self): ...
    async def __aexit__(self, *args) -> None: ...
    def create_client(self) -> Client: ...
    def execute(self, function: Function[T]) -> T: ...
    def attach_dispatcher(self, dp: Dispatcher): ...
    def init(self) -> None: ...
    async def join(self) -> None: ...
    async def shutdown(self) -> None: ...
